 drop table public.recipe_binary if exists;

 create table public.recipe_binary (
       id bigint generated by default as identity,
        binary_description binary(100000),
        binary_description_checksum varchar(255),
        primary key (id)
    );